### ISSUE TITLE
easy way to install

### ISSUE THREAD

**Issue by baoxingsong** [xiaochuanle/MECAT2#1]
I am testing mecat2 under docker

I failed to compile and solved by adding to addition two standard libraries to src/fsa/utility.hpp 
#include <numeric>
#include <cmath>

Failed to install dextract using the method on your document, while dextract could be installed easily using conda

**Comment by xiaochuanle** [comment]
The problem is solved. Alternatively, we also upload a binary version of MECAT2 in case the users have any trouble when installing MECAT2.
