### ISSUE TITLE
How to extract longest 30x corrected reads from corrected reads generated by other soft

### ISSUE THREAD

**Issue by SC-Duan** [xiaochuanle/MECAT2#10]
Hi,
I corrected the raw reads using other soft, because the  two flanking un-corrected sequences have been trimed in my result, I change the fasta sequences' ID like ">A_B_C_D", here,

A is the original read id;
B is the left-most effective position, I set as 0;
C is the right-most effective position,  I set as the read's length;
D is the length of the corrected sequence,  I set as the read's length;

However, when I run "extract_sequences corrected.fasta corrected_30x 400000000 30" in MECAT, I get the error message below,
"extract_sequences error: [main, 53] system() error. Error code is 139."
Can you give me some help?
Thank you!

**Comment by xiaochuanle** [comment]
You do not have to change the header format.  Running
```shell
MECAT2/Linux-amd64/bin/mecat2elr corrected.fasta 400000000 30 corrected_30x.fasta
```
will give you the desired results.
