### ISSUE TITLE
fsa_ol_filter: No such file or directory

### ISSUE THREAD

**Issue by zijiangyang** [xiaochuanle/MECAT2#12]
Hi, when I run the ass_job.sh script it returned an error "/mecat2/pnoto/scripts/ass_job.sh: line 6: /mecat2/MECAT2/Linux-amd64/bin/fsa_ol_filter: No such file or directory   [Error] Failed to run script, 127, /mecat2/pnoto/scripts/ass_job.sh". I checked the bin directory and didn't find the required file "fsa_ol_filter", May I ask where can I get that file?

Thanks in advance!

**Comment by xiaochuanle** [comment]
Please make sure you have compiled MECAT2 successfully. And please show me the result of the following command
```shell
ls  /mecat2/MECAT2/Linux-amd64/bin/
```
Or you can download the executable binaries (step 2 of installation) to get rid of the compiling process.

**Comment by zijiangyang** [comment]
> Please make sure you have compiled MECAT2 successfully. And please show me the result of the following command
> ls  /mecat2/MECAT2/Linux-amd64/bin/
> Or you can download the executable binaries (step 2 of installation) to get rid of the compiling process.

Hi, here are the results 
`filter_reads  mecat2cns  mecat2pw   mecat.pl  Plgd     v2asmpm.sh  v2mkvol  v2sr  v2trim.sh libmecat.a    mecat2elr  mecat2ref  mecat.sh  v2asmpm  v2lcr       v2pm4    v2tb`

I used git clone to install the mecat2 and follows the instructions, strange..
