### ISSUE TITLE
Regarding parameter sweep for repetitive genomes

### ISSUE THREAD

**Issue by harish0201** [xiaochuanle/MECAT2#3]
Hi,

I'm currently assembling a large repetitive genome (2.4Gb). Genome scope estimates show that we are looking at 85-90% repeats. What parameters would you suggest us?

I'm planning to run MECAT2, but I need to reserve adequate resource, so I was wondering.

The brief subreads stats are as follows:
N50 length: 16Kb; Avg length: 10Kb; Median length: 7.48Kb, #sum_data: 160Gb

**Comment by xiaochuanle** [comment]
I suppose by 160Gb you mean the total bps of raw reads. Then you have a 67X sequencing data, which admits a relative relaxed parameter setting. In this case you can use the following options in config file:
```shell
MIN_READ_LENGTH=3000
CNS_OPTIONS="-r 0.8 -a 2000 -c 4 -l 3000"
```
Otherwise if 160Gb is the size of a fastq format file, just use the default parameter setting.

**Comment by harish0201** [comment]
Sorry, somehow missed the notification, the data generated is 160Gb (total bases in the data)

**Comment by harish0201** [comment]
I have been able to run and the correction has finished successfully. However, I did get a seg-fault. Let me know what logs do I have to extract so that we can resolve this issue.

2019-04-01 10:17:06 [Info] Parallelly start aligning volumn 37 for trimming.
2019-04-01 10:17:06 [Info] Run script: /SANbackup/Pacbio_data/mecat_pipe/genome/scripts/tr_al_vol_36.sh 2>&1 |tee /SANbackup/Pacbio_data/mecat_pipe/genome/scripts/tr_al_vol_36.sh.log
/SANbackup/Pacbio_data/mecat_pipe/genome/scripts/tr_al_vol_36.sh: line 11: 71756 Segmentation fault      /SANbackup/Pacbio_data/MECAT2/Linux-amd64/bin/v2asmpm -P/SANbackup/Pacbio_data/mecat_pipe/shrimp/2-trim_bases/trim_pm_dir -T80 -S37
-E37 -B
2019-04-01 10:17:23 [Error] Failed to run script, 139, /SANbackup/Pacbio_data/mecat_pipe/genome/scripts/tr_al_vol_36.sh
/SANbackup/Pacbio_data/mecat_pipe$ /SANbackup/Pacbio_data/mecat_pipe/genome/scripts/tr_al_vol_36.sh
finished reading params
/SANbackup/Pacbio_data/mecat_pipe/genome/scripts/tr_al_vol_36.sh: line 11: 45240 Segmentation fault      /SANbackup/Pacbio_data/MECAT2/Linux-amd64/bin/v2asmpm -P/SANbackup/Pacbio_data/mecat_pipe/genome/2-trim_bases/trim_pm_dir -T80 -S37 -E37 -B
