### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by mawad89** [xiaochuanle/MECAT2#4]
I assembled a genome using MECAT2 following quick start guide 
`mecat.pl config config.txt`
`mecat.pl correct config.txt`
after this step this script has been run `cns_pw.sh`, and produced `cns_pm.can` and `cns_pm_dir` in `1-consensus`
`mecat.pl assemble config.txt`
after this step this script has been run `cns_cns.sh`, and produced `cns_reads.fasta`, `cns_pm.can.partition_files` and `cns_pm.can.part0`:17 in the same folder `1-consensus`
I can't find final.fasta, trimed.fasta or contig.fasta
where is the error?

**Comment by xiaochuanle** [comment]
Please show me the output log of mecat  to tell where mecat stops, or what error occurs.

**Comment by mawad89** [comment]
This is the last lines in log file

Lid = 0, Rid = 3000000
/home/aw/aw_false/scripts/cns_cns.sh: line 11:  4112 Aborted
/home/mecat2/MECAT2/Linux-amd64/bin/mecat2cns -i 0 -t 20 -r 0.6 -a 1000 -c 4 -l 2000 /home/aw/aw_false/1-consensus/cns_pm.can /home/aw/all.fastq /home/aw/aw_false/1-consensus/cns_reads.fasta
2019-03-27 01:24:38 [Error] Failed to run script, 134, /home/aw/aw_false/scripts/cns_cns.sh

**Comment by xiaochuanle** [comment]
This error always occurs in the first released version. Please make sure you are using the latest version. For example, if you use the executable binaries, you should use
```shell
https://github.com/xiaochuanle/MECAT2/releases/download/v20190314/mecat_20190314_Linux-amd64.tar.gz
```
but not
``` shell
https://github.com/xiaochuanle/MECAT2/releases/download/20192026/mecat2_20190226_linuax_amd64.tar.gz
```
On the other hand, if you build from source codes, please make sure you are using the latest codes.
