### ISSUE TITLE
calloc fail

### ISSUE THREAD

**Issue by mr--white** [xiaochuanle/MECAT2#7]
I tried testing with the provided  ecoli_filtered.fastq.gz data.  I'm using the precompiled binaries as well.  I get the Aborted (core dumped) message during the 'correct' step.  I'm running this from a singularity container.  I've also tried it using the source and compiling it locally but the result is the same.  I'm not sure what i may be doing wrong.

Singularity mecat2.test:> mecat.pl correct ecoli_config_file.txt
Smartmatch is experimental at /usr/local/MECAT2/Linux-amd64/bin/Plgd/Project.pm line 232.
2019-04-05 00:28:03 [Info] Start correcting rawreads.
2019-04-05 00:28:03 [Info] Start correcting rawreads step 1 mecat2pw.
2019-04-05 00:28:03 [Info] Run script: /usr/local/ecoli/ecoli/scripts/cns_pw.sh 2>&1 |tee /usr/local/ecoli/ecoli/scripts/cns_pw.sh.log
[split_raw_dataset] begins.
[split_raw_dataset, 265] split '/usr/local/ecoli/ecoli_filtered.fastq' (47910 reads, 396827122 nucls) into 1 volumes.
[split_raw_dataset] takes 4.10 secs.
[create_ref_index] begins.
[create_ref_index, 70] calloc fail
/usr/local/ecoli/ecoli/1-consensus/cns_pm_dir/fileindex.txt
/usr/local/ecoli/ecoli/scripts/cns_pw.sh: line 11: 217053 Aborted                 (core dumped) /usr/local/MECAT2/Linux-amd64/bin/mecat2pw -j 0 -d /usr/loca
l/ecoli/ecoli_filtered.fastq -o /usr/local/ecoli/ecoli/1-consensus/cns_pm.can -w /usr/local/ecoli/ecoli/1-consensus/cns_pm_dir -t 4
2019-04-05 00:28:08 [Error] Failed to run script, 134, /usr/local/ecoli/ecoli/scripts/cns_pw.sh

**Comment by xiaochuanle** [comment]
It is likely that your computer do not have enough main memory.
