### ISSUE TITLE
about the output meaning

### ISSUE THREAD

**Issue by zwyy5520** [xiaochuanle/MECAT2#8]
![image](https://user-images.githubusercontent.com/48539334/55710130-7fba2300-5a1c-11e9-805f-d0db3070c258.png)

Hi 
  I performed a genome assemble using the MECAT2 and got the result as the picture above in the file "4-fsa/contigs.fasta" ,but I am wondering the meaning of the sequence type in red frame and want to know if i don't want one of those types appear,what should I do ?
  Thanks a lot !

**Comment by xiaochuanle** [comment]
circular: the contig is a circular
linear: the contig is not a circular
stub: there exist ambiguities in the contig, probability repetitive subsequences.

It is currently not supported to output a specified type of contigs.
